apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      task: monitoring
      k8s-app: heapster
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: registry.cn-hangzhou.aliyuncs.com/docker_gjt/heapster:v1.5.3
        volumeMounts:
        - mountPath: /usr/local/kubernetes/certs
          name: auth
        - mountPath: /usr/local/kubernetes/config
          name: config
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default?inClusterConfig=false&insecure=true&auth=/usr/local/kubernetes/config/kubeconfig
        - --sink=influxdb:http://192.168.5.103:31001
     volumes:
      - name: auth
        hostPath:
          path: /usr/local/kubernetes/certs
      - name: config
        hostPath:
          path: /usr/local/kubernetes/config
